#!/bin/sh

SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/rJava
echo "Copying package base ..."
cp -r ../rJava /tmp

rm /tmp/rJava/mkdist
rm -f /tmp/rJava/*~ /tmp/rJava/R/*~ /tmp/rJava/src/*~ /tmp/rJava/man/*~

cd /tmp/rJava
if [ -e /tmp/rJava/configure ]; then
    echo "Note: autoreconf is *not* ran automatically if configure exists."
    echo "      Run it manually if necessary."
else 
    echo "Running autoreconf ..."
    autoreconf
    rm -rf autom4te*
fi

echo "Removing CVS stuff ..."
rm -rf `find . -name CVS`
cd ..

#echo "Updating INDEX ..."
# R CMD Rdindex rJava > rJava/INDEX
#echo "library(tools)\nsink(\"rJava/INDEX\")\nRdindex(\"rJava/man\")\nsink()" | R --vanilla > /dev/null

echo "Updating version ..."
cd rJava
VER=`awk -v ORS= '/rJava v/ { print substr($6,2) }' src/rJava.h`
echo "rJava version ${VER}"
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz rJava_${VER}.tar.gz rJava
cd ${SWD}
cp /tmp/rJava_${VER}.tar.gz ..
rm -rf /tmp/rJava
echo "Done."
ls -l ../rJava_${VER}.tar.gz
